type: object
required:
  - quotationTerm
  - quotationPeriod
properties:
  quotationDays:
    type: integer
    format: int32
    description: Indica se o fundo estabelece um período em que o investidor não pode resgatar os recursos aplicados no fundo. Caso ocorra resgate antes do período, o investidor perderá a rentabilidade do período.
    minimum: 0
    example: 60
  quotationTerm:
    type: integer
    format: int32
    description: Prazo em dias de cotização da aplicação.
    minimum: 0
    example: 3
  quotationPeriod:
    $ref: ../enum/EnumInvestmentsFundGeneralConditionsTermType.yaml