openapi: 3.0.0
info:
  title: API Investments - Open Banking Brasil
  description: |
    Estas APIs visam o compartilhamento de dados sobre Investimentos e suas
    características entre as Instituições Financeiras participantes do Open Banking Brasil
  version: 1.0.0
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
  contact:
    name: Governança do Open Banking Brasil – Especificações
    email: gt-interfaces@openbankingbr.org
    url: 'https://openbanking-brasil.github.io/areadesenvolvedor/'
servers:
  - url: 'https://api.banco.com.br/open-banking/investments/v1'
    description: Servidor de Produção
  - url: 'https://apih.banco.com.br/open-banking/investments/v1'
    description: Servidor de Homologação
tags:
  - name: Funds
    description: Método para obter a lista de Fundos de Investimentos
  - name: Fixed Income Bank
    description: Método para obter a lista de produtos de Renda Fixa Bancária (CDB, RDB, LCI e LCA)
  - name: Fixed Income Credit
    description: Método para obter a lista de produtos de Renda Fixa Crédito (Debênture, CRI e CRA)
  - name: Variable Income
    description: Método para obter a lista de informações de produtos de Renda Variável (Ações e Fundos de Índices)
  - name: Treasure
    description: Método para obter informações de Títulos do Tesouro Direto
paths:
  /funds:
    get:
      tags:
        - Funds
      summary: Conjunto de informações dos Fundos de Investimentos
      operationId: investmentsGetFunds
      description: Método para obter a lista de Fundos de Investimentos
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseInvestmentsFund'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /fixed-income-bank:
    get:
      tags:
        - Fixed Income Bank
      summary: Conjunto de informações de produtos de Renda Fixa Bancária (CDB, RDB, LCI e LCA)
      operationId: investmentsGetFixedIncomeBank
      description: Método para obter a lista de produtos de Renda Fixa Bancária (CDB, RDB, LCI e LCA)
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseInvestmentsFixedIncomeBank'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /fixed-income-credit:
    get:
      tags:
        - Fixed Income Credit
      summary: Conjunto de informações de produtos de Renda Fixa Crédito (Debênture, CRI e CRA)
      operationId: investmentsGetFixedIncomeCredit
      description: Método para obter a lista de produtos de Renda Fixa Crédito (Debênture, CRI e CRA)
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseInvestmentsFixedIncomeCredit'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /variable-income:
    get:
      tags:
        - Variable Income
      summary: Conjunto de informações de produtos de Renda Variável (Ações e Fundos de Índices)
      operationId: investmentsGetVariableIncome
      description: Método para obter a lista de informações de produtos de Renda Variável (Ações e Fundos de Índices)
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseInvestmentsVariableIncome'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /treasure:
    get:
      tags:
        - Treasure
      summary: Conjunto de informações de Títulos do Tesouro Direto
      operationId: investmentsGetTreasure
      description: Método para obter informações de Títulos do Tesouro Direto
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseInvestmentsTreasure'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    OKResponseInvestmentsFund:
      $ref: ./schemas/investments_apis/ResponseInvestmentsFund.yaml
    OKResponseInvestmentsFixedIncomeBank:
      $ref: ./schemas/investments_apis/ResponseInvestmentsFixedIncomeBank.yaml
    OKResponseInvestmentsFixedIncomeCredit:
      $ref: ./schemas/investments_apis/ResponseInvestmentsFixedIncomeCredit.yaml
    OKResponseInvestmentsVariableIncome:
      $ref: ./schemas/investments_apis/ResponseInvestmentsVariableIncome.yaml
    OKResponseInvestmentsTreasure:
      $ref: ./schemas/investments_apis/ResponseInvestmentsTreasure.yaml
    InvestmentsFixedIncomeBank:
      $ref: ./schemas/investments_apis/InvestmentsFixedIncomeBank.yaml
    InvestmentsFixedIncomeBankIndex:
      $ref: ./schemas/investments_apis/InvestmentsFixedIncomeBankIndex.yaml
    InvestmentsFixedIncomeBankInvestmentConditions:
      $ref: ./schemas/investments_apis/InvestmentsFixedIncomeBankInvestmentConditions.yaml
    InvestmentsFixedIncomeBankProductIdentification:
      $ref: ./schemas/investments_apis/InvestmentsFixedIncomeBankProductIdentification.yaml
    InvestmentsFixedIncomeCredit:
      $ref: ./schemas/investments_apis/InvestmentsFixedIncomeCredit.yaml
    InvestmentsFixedIncomeCreditFees:
      $ref: ./schemas/investments_apis/InvestmentsFixedIncomeCreditFees.yaml
    InvestmentsFund:
      $ref: ./schemas/investments_apis/InvestmentsFund.yaml
    InvestmentsFundFees:
      $ref: ./schemas/investments_apis/InvestmentsFundFees.yaml
    InvestmentsFundGeneralConditions:
      $ref: ./schemas/investments_apis/InvestmentsFundGeneralConditions.yaml
    InvestmentsFundProduct:
      $ref: ./schemas/investments_apis/InvestmentsFundProduct.yaml
    InvestmentsTreasure:
      $ref: ./schemas/investments_apis/InvestmentsTreasure.yaml
    InvestmentsTreasureFees:
      $ref: ./schemas/investments_apis/InvestmentsTreasureFees.yaml
    InvestmentsVariableIncome:
      $ref: ./schemas/investments_apis/InvestmentsVariableIncome.yaml
    InvestmentsVariableIncomeFees:
      $ref: ./schemas/investments_apis/InvestmentsVariableIncomeFees.yaml
    EnumInvestmentsFixedIncomeBankIndexer:
      $ref: ./schemas/enum/EnumInvestmentsFixedIncomeBankIndexer.yaml
    EnumInvestmentsFixedIncomeBankProductType:
      $ref: ./schemas/enum/EnumInvestmentsFixedIncomeBankProductType.yaml
    EnumInvestmentsFixedIncomeBankRedemptionTerm:
      $ref: ./schemas/enum/EnumInvestmentsFixedIncomeBankRedemptionTerm.yaml
    EnumInvestmentsFixedIncomeCreditInvestmentType:
      $ref: ./schemas/enum/EnumInvestmentsFixedIncomeCreditInvestmentType.yaml
    EnumInvestmentsFundFeesPerformanceFeeBenchmark:
      $ref: ./schemas/enum/EnumInvestmentsFundFeesPerformanceFeeBenchmark.yaml
    EnumInvestmentsFundFeesPerformanceFeeMethod:
      $ref: ./schemas/enum/EnumInvestmentsFundFeesPerformanceFeeMethod.yaml
    EnumInvestmentsFundGeneralConditionsFundQuotaType:
      $ref: ./schemas/enum/EnumInvestmentsFundGeneralConditionsFundQuotaType.yaml
    EnumInvestmentsFundGeneralConditionsTermType:
      $ref: ./schemas/enum/EnumInvestmentsFundGeneralConditionsTermType.yaml
    EnumInvestmentsFundProductAnbimaCategory:
      $ref: ./schemas/enum/EnumInvestmentsFundProductAnbimaCategory.yaml
    EnumInvestmentsFundTaxation:
      $ref: ./schemas/enum/EnumInvestmentsFundTaxation.yaml
    EnumInvestmentsTreasureInvestmentType:
      $ref: ./schemas/enum/EnumInvestmentsTreasureInvestmentType.yaml
    EnumInvestmentsVariableIncomeInvestmentType:
      $ref: ./schemas/enum/EnumInvestmentsVariableIncomeInvestmentType.yaml
    InvestmentsParticipantIdentification:
      $ref: ./schemas/business_commons/ParticipantIdentification.yaml
  parameters:
    page:
      $ref: ./parameters/Page.yaml
    pageSize:
      $ref: ./parameters/PageSize.yaml
  responses:
    OKResponseInvestmentsFund:
      description: Dados de fundos de investimentos obtidos com sucesso.
      content:
        application/json:
          schema:
            $ref: ./schemas/investments_apis/ResponseInvestmentsFund.yaml
    OKResponseInvestmentsFixedIncomeBank:
      description: Dados de produtos de renda fixa bancária obtidos com sucesso.
      content:
        application/json:
          schema:
            $ref: ./schemas/investments_apis/ResponseInvestmentsFixedIncomeBank.yaml
    OKResponseInvestmentsFixedIncomeCredit:
      description: Dados de produtos de renda fixa crédito obtidos com sucesso.
      content:
        application/json:
          schema:
            $ref: ./schemas/investments_apis/ResponseInvestmentsFixedIncomeCredit.yaml
    OKResponseInvestmentsVariableIncome:
      description: Dados de produtos de renda variável obtidos com sucesso.
      content:
        application/json:
          schema:
            $ref: ./schemas/investments_apis/ResponseInvestmentsVariableIncome.yaml
    OKResponseInvestmentsTreasure:
      description: Dados de títulos do tesouro direto obtidos com sucesso.
      content:
        application/json:
          schema:
            $ref: ./schemas/investments_apis/ResponseInvestmentsTreasure.yaml
    BadRequest:
      description: 'A requisição foi malformada, omitindo atributos obrigatórios, seja no payload ou através de atributos na URL.'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    InternalServerError:
      description: Ocorreu um erro no gateway da API ou no microsserviço
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    MethodNotAllowed:
      description: O consumidor tentou acessar o recurso com um método não suportado
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    NotFound:
      description: O recurso solicitado não existe ou não foi implementado
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    TooManyRequests:
      description: 'A operação foi recusada, pois muitas solicitações foram feitas dentro de um determinado período ou o limite global de requisições concorrentes foi atingido'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
