openapi: 3.0.0
info:
  title: Fase 4 - APIs do Open Banking Brasil
  description: |
    Estas APIs visam o compartilhamento de dados sobre Títulos de Capitalização e suas características entre as Instituições Financeiras participantes do Open Banking Brasil.

  version: 1.0.0-rc1.0
tags:
  - name: API - Titulos de Capitalização
    description: |
      |Versão|
      |:-----|
      |1.0.0-rc1.0|

      #### Visão Geral

      As instituições financeiras participantes podem consultar a lista de Títulos de Capitalização de outras instituições participantes. 
      
      #### Especificação em OAS 3.0

      <a href="swagger/swagger_capitalization_bonds_apis.yaml" target="_blank">Download da Especificação (OAS 3.0)</a>

paths:
  /capitalization-bonds/v1/products:
    get:
      tags:
        - API - Titulos de Capitalização
      summary: Conjunto de informações dos Títulos de Capitalização.
      operationId: capitalizationBondsGetProducts
      description: |
        Método para obter a lista de Títulos de Capitalização.
        
        ### Dicionário de dados

        Campos de resposta do endpoint de `/products`

        <a href='dictionary/capitalizationBondsGetProducts_v1.csv' target="_blank">Fazer download do dicionário de dados</a>

        Consulte a seção **Convenções de payload** para obter mais informações sobre [Atributos Obrigatórios / Opcionais](#convencoes-de-propriedade-dos-atributos).

      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseCapitalizationBondsProductsList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/OKResponseCapitalizationBondsProductsList'
  /capitalization-bonds/v1/products/{productId}:
    get:
      tags:
        - API - Titulos de Capitalização
      summary: Obtém os dados do Título de Capitalização por productId.
      operationId: capitalizationBondsGetProductsProductId
      description: |
        Método para obter os dados do Título de Capitalização por productId.
        
        ### Dicionário de dados

        Campos de resposta do endpoint de `/products/{productId}`

        <a href='dictionary/capitalizationBondsGetProductsProductId_v1.csv' target="_blank">Fazer download do dicionário de dados</a>

        Consulte a seção **Convenções de payload** para obter mais informações sobre [Atributos Obrigatórios / Opcionais](#convencoes-de-propriedade-dos-atributos).

      parameters:
        - $ref: '#/components/parameters/productId'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseCapitalizationBondsProductIdentification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/OKResponseCapitalizationBondsProductIdentification'
components:
  schemas:
    ResponseCapitalizationBondsProductsList:
      $ref: ./schemas/capitalization_bonds_apis/ResponseCapitalizationBondsProductsList.yaml
    CapitalizationBondsProductData:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProductData.yaml
    CapitalizationBondsParticipantIdentification:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsParticipantIdentification.yaml
    CapitalizationBondsInsuranceCompanyIdentification:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsInsuranceCompanyIdentification.yaml
    CapitalizationBondsProduct:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProduct.yaml
    EnumCapitalizationBondsProductModality:
      $ref: ./schemas/enum/EnumCapitalizationBondsProductModality.yaml
    EnumCapitalizationBondsProductPaymentFrequency:
      $ref: ./schemas/enum/EnumCapitalizationBondsProductPaymentFrequency.yaml
    ResponseCapitalizationBondsProductIdentification:
      $ref: ./schemas/capitalization_bonds_apis/ResponseCapitalizationBondsProductIdentification.yaml
    Links:
      $ref: ./schemas/Links.yaml
    Meta:
      $ref: ./schemas/Meta.yaml
    ResponseError:
      $ref: ./schemas/ResponseError.yaml
    XFapiInteractionId:
      $ref: ./headers/XFapiInteractionId.yaml
  parameters:
    page:
      $ref: ./parameters/Page.yaml
    pageSize:
      $ref: ./parameters/PageSize.yaml
    productId:
      $ref: ./parameters/CapitalizationBondsProductId.yaml
  responses:
    OKResponseCapitalizationBondsProductsList:
      description: Conjunto de informações das Contas de pagamento pós paga
      headers:
        x-fapi-interaction-id:
          schema:
            $ref: '#/components/schemas/XFapiInteractionId'
      content:
        application/json:
          schema:
            $ref: ./schemas/capitalization_bonds_apis/ResponseCapitalizationBondsProductsList.yaml
    OKResponseCapitalizationBondsProductIdentification:
      description: Dados de identificação da conta identificada por creditCardAccountId obtidos com sucesso.
      headers:
        x-fapi-interaction-id:
          schema:
            $ref: '#/components/schemas/XFapiInteractionId'
      content:
        application/json:
          schema:
            $ref: ./schemas/capitalization_bonds_apis/ResponseCapitalizationBondsProductIdentification.yaml
    BadRequest:
      description: 'A requisição foi malformada, omitindo atributos obrigatórios, seja no payload ou através de atributos na URL.'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    Forbidden:
      description: O token tem escopo incorreto ou uma política de segurança foi violada
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    InternalServerError:
      description: Ocorreu um erro no gateway da API ou no microsserviço
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    MethodNotAllowed:
      description: O consumidor tentou acessar o recurso com um método não suportado
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    NotAcceptable:
      description: A solicitação continha um cabeçalho Accept diferente dos tipos de mídia permitidos ou um conjunto de caracteres diferente de UTF-8
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    NotFound:
      description: O recurso solicitado não existe ou não foi implementado
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    TooManyRequests:
      description: 'A operação foi recusada, pois muitas solicitações foram feitas dentro de um determinado período ou o limite global de requisições concorrentes foi atingido'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    Unauthorized:
      description: Cabeçalho de autenticação ausente/inválido ou token inválido
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
