openapi: 3.0.0
info:
  title: Fase 4 - APIs do Open Banking Brasil
  description: |
    ### Sub titulo fase 4...

    Na fase 4 do Open Banking Brasil........

  version: 1.0.0-rc1.0
tags:
  - name: API - Titulos de Capitalização
    description: |
      |Versão|
      |:-----|
      |1.0.0-rc1.0|

      #### Visão Geral

      A API tem como objetivo .....

      #### Especificação em OAS 3.0

      <a href="swagger/swagger_capitalization_bonds_apis.yaml" target="_blank">Download da Especificação (OAS 3.0)</a>

paths:
  /capitalization-bonds/v1/products:
    post:
      tags:
        - API - Titulos de Capitalização
      summary: Conjunto de informações dos Títulos de Capitalização.
      description: Método para obter a lista de Títulos de Capitalização.
      parameters:
        - $ref: '#/components/parameters/Authorization'
        - $ref: '#/components/parameters/xFapiAuthDate'
        - $ref: '#/components/parameters/xFapiCustomerIpAddress'
        - $ref: '#/components/parameters/xFapiInteractionId'
        - $ref: '#/components/parameters/xCustomerUserAgent'
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseCapitalizationBondsProductsList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '406':
          $ref: '#/components/responses/NotAcceptable'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
        default:
          $ref: '#/components/responses/OKResponseCapitalizationBondsProductsList'
      security:
        - OpenId:
            - 'openid'
          OAuth2Security:
            - 'consent:consentId'
            - 'credit-cards-accounts' 
components:
  schemas:
    ResponseCapitalizationBondsProductsList:
      $ref: ./schemas/capitalization_bonds_apis/ResponseCapitalizationBondsProductsList.yaml
    
    CapitalizationBondsProductData:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProductData.yaml

    CapitalizationBondsParticipantIdentification:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsParticipantIdentification.yaml

    CapitalizationBondsInsuranceCompanyIdentification:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsInsuranceCompanyIdentification.yaml

    CapitalizationBondsProduct:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProduct.yaml

    EnumCapitalizationBondsProductModality:
      $ref: ./schemas/enum/EnumCapitalizationBondsProductModality.yaml

    EnumCapitalizationBondsProductPaymentFrequency:
      $ref: ./schemas/enum/EnumCapitalizationBondsProductPaymentFrequency.yaml

    ResponseCapitalizationBondsProductIdentification:
      $ref: ./schemas/capitalization_bonds_apis/ResponseCapitalizationBondsProductIdentification.yaml


    # CreditCardsAccountsIdentificationData:
    #   $ref: ./schemas/credit_cards_apis/CreditCardsAccountsIdentificationData.yaml
    # CreditCardAccountsBillsData:
    #   $ref: ./schemas/credit_cards_apis/CreditCardAccountsBillsData.yaml
    # CreditCardAccountsBillsFinanceCharge:
    #   $ref: ./schemas/credit_cards_apis/CreditCardAccountsBillsFinanceCharge.yaml
    # CreditCardAccountsBillsPayment:
    #   $ref: ./schemas/credit_cards_apis/CreditCardAccountsBillsPayment.yaml
    # CreditCardAccountsData:
    #   $ref: ./schemas/credit_cards_apis/CreditCardAccountsData.yaml
    # CreditCardAccountsLimitsData:
    #   $ref: ./schemas/credit_cards_apis/CreditCardAccountsLimitsData.yaml
    # CreditCardsAccountPaymentMethod:
    #   $ref: ./schemas/credit_cards_apis/CreditCardsAccountsPaymentMethod.yaml
    # CreditCardAccountsTransaction:
    #   $ref: ./schemas/credit_cards_apis/CreditCardAccountsTransaction.yaml
    # EnumCreditCardAccountFee:
    #   $ref: ./schemas/enum/EnumCreditCardAccountFee.yaml
    # EnumCreditCardAccountsBillingValueType:
    #   $ref: ./schemas/enum/EnumCreditCardAccountsBillingValueType.yaml
    # EnumCreditCardAccountsConsolidationType:
    #   $ref: ./schemas/enum/EnumCreditCardAccountsConsolidationType.yaml
    # EnumCreditCardAccountsFinanceChargeType:
    #   $ref: ./schemas/enum/EnumCreditCardAccountsFinanceChargeType.yaml
    # EnumCreditCardAccountsLineLimitType:
    #   $ref: ./schemas/enum/EnumCreditCardAccountsLineLimitType.yaml
    # EnumCreditCardAccountsLineName:
    #   $ref: ./schemas/enum/EnumCreditCardAccountsLineName.yaml
    # EnumCreditCardAccountNetwork:
    #   $ref: ./schemas/enum/EnumCreditCardAccountNetwork.yaml
    # EnumCreditCardAccountsOtherCreditType:
    #   $ref: ./schemas/enum/EnumCreditCardAccountsOtherCreditType.yaml
    # EnumCreditCardAccountsPaymentMode:
    #   $ref: ./schemas/enum/EnumCreditCardAccountsPaymentMode.yaml
    # EnumCreditCardAccountsPaymentType:
    #   $ref: ./schemas/enum/EnumCreditCardAccountsPaymentType.yaml
    # EnumCreditCardAccountsProductType:
    #   $ref: ./schemas/enum/EnumCreditCardAccountsProductType.yaml
    # EnumCreditCardTransactionType:
    #   $ref: ./schemas/enum/EnumCreditCardTransactionType.yaml
    # EnumCreditDebitIndicator:
    #   $ref: ./schemas/enum/EnumCreditDebitIndicator.yaml
    Links:
      $ref: ./schemas/Links.yaml
    Meta:
      $ref: ./schemas/Meta.yaml
    # ResponseCreditCardAccountsList:
    #   $ref: ./schemas/credit_cards_apis/ResponseCreditCardAccountsList.yaml
    # ResponseCreditCardAccountsBills:
    #   $ref: ./schemas/credit_cards_apis/ResponseCreditCardAccountsBills.yaml
    # ResponseCreditCardAccountsIdentification:
    #   $ref: ./schemas/credit_cards_apis/ResponseCreditCardAccountsIdentification.yaml
    # ResponseCreditCardAccountsLimits:
    #   $ref: ./schemas/credit_cards_apis/ResponseCreditCardAccountsLimits.yaml
    # ResponseCreditCardAccountsTransactions:
    #   $ref: ./schemas/credit_cards_apis/ResponseCreditCardAccountsTransactions.yaml
    ResponseError:
      $ref: ./schemas/ResponseError.yaml
    XFapiInteractionId:
      $ref: ./headers/XFapiInteractionId.yaml
  parameters:
    Authorization:
      $ref: ./parameters/Authorization.yaml
    creditCardAccountId:
      $ref: ./parameters/CreditCardAccountId.yaml
    page:
      $ref: ./parameters/Page.yaml
    pageSize:
      $ref: ./parameters/PageSize.yaml
    xCustomerUserAgent:
      $ref: ./parameters/XCustomerUserAgent.yaml
    xFapiAuthDate:
      $ref: ./parameters/XFapiAuthDate.yaml
    xFapiCustomerIpAddress:
      $ref: ./parameters/XFapiCustomerIpAddress.yaml
    xFapiInteractionId:
      $ref: ./parameters/XFapiInteractionId.yaml

  securitySchemes:
    OpenId:
      type: openIdConnect
      openIdConnectUrl: 'https://auth.mockbank.poc.raidiam.io/.well-known/openid-configuration'
    OAuth2Security:
      type: oauth2
      description: "Fluxo OAuth necessário para que a receptora tenha acesso aos dados na instituição transmissora. Requer o processo de redirecionamento e autenticação do usuário a que se referem os dados."
      flows:
        authorizationCode:
          authorizationUrl: "https://authserver.example/authorization"
          tokenUrl: "https://authserver.example/token"
          scopes:
            credit-cards-accounts: "Escopo necessário para acesso à API Credit-cards-accounts. O controle dos endpoints específicos é feito via permissions."

  responses:
    OKResponseCapitalizationBondsProductsList:
      description: Conjunto de informações das Contas de pagamento pós paga
      headers:
        x-fapi-interaction-id:
          schema:
            $ref: '#/components/schemas/XFapiInteractionId'
      content:
        application/json:
          schema:
            $ref: ./schemas/capitalization_bonds_apis/ResponseCapitalizationBondsProductsList.yaml
    OKResponseCapitalizationBondsProductIdentification:
      description: Dados de identificação da conta identificada por creditCardAccountId obtidos com sucesso.
      headers:
        x-fapi-interaction-id:
          schema:
            $ref: '#/components/schemas/XFapiInteractionId'
      content:
        application/json:
          schema:
            $ref: ./schemas/capitalization_bonds_apis/ResponseCapitalizationBondsProductIdentification.yaml
    BadRequest:
      description: 'A requisição foi malformada, omitindo atributos obrigatórios, seja no payload ou através de atributos na URL.'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    Forbidden:
      description: O token tem escopo incorreto ou uma política de segurança foi violada
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    InternalServerError:
      description: Ocorreu um erro no gateway da API ou no microsserviço
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    MethodNotAllowed:
      description: O consumidor tentou acessar o recurso com um método não suportado
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    NotAcceptable:
      description: A solicitação continha um cabeçalho Accept diferente dos tipos de mídia permitidos ou um conjunto de caracteres diferente de UTF-8
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    NotFound:
      description: O recurso solicitado não existe ou não foi implementado
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    TooManyRequests:
      description: 'A operação foi recusada, pois muitas solicitações foram feitas dentro de um determinado período ou o limite global de requisições concorrentes foi atingido'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    Unauthorized:
      description: Cabeçalho de autenticação ausente/inválido ou token inválido
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
