openapi: 3.0.0
info:
  title: Fase 4 - APIs do Open Banking Brasil
  description: |
    Estas APIs visam o compartilhamento de dados sobre Títulos de Capitalização e suas
    características entre as Instituições Financeiras participantes do Open Banking Brasil
  version: 1.0.0-rc1.0
tags:
  - name: API - Títulos de Capitalização
    description: |
      |Versão|
      |:-----|
      |1.0.0-rc1.0|

      #### Visão Geral

      As instituições financeiras participantes podem consultar a lista de Títulos de Capitalização de outras instituições participantes

      #### Especificação em OAS 3.0

      <a href="swagger/swagger_capitalization_bonds_apis.yaml" target="_blank">Download da Especificação (OAS 3.0)</a>

  - name: API - Investimentos - Fundos de Investimentos
    description: |
      |Versão|
      |:-----|
      |1.0.0|

      #### Visão Geral

      As instituições financeiras participantes podem consultar a lista de Fundos de Investimentos de outras instituições participantes

      #### Especificação em OAS 3.0

      <a href="swagger/swagger_investments_funds_apis.yaml" target="_blank">Download da Especificação (OAS 3.0)</a>

  - name: API - Investimentos - CDB, RDB, LCI e LCA
    description: |
      |Versão|
      |:-----|
      |1.0.0|

      #### Visão Geral

      As instituições financeiras participantes podem consultar a lista de produtos de Renda Fixa Bancária de outras instituições participantes

      #### Especificação em OAS 3.0

      <a href="swagger/swagger_investments_fixed_income_bank_apis.yaml" target="_blank">Download da Especificação (OAS 3.0)</a>

  - name: API - Investimentos - Debênture, CRI e CRA
    description: |
      |Versão|
      |:-----|
      |1.0.0|

      #### Visão Geral

      As instituições financeiras participantes podem consultar a lista de produtos de Renda Fixa Crédito de outras instituições participantes

      #### Especificação em OAS 3.0

      <a href="swagger/swagger_investments_fixed_income_credit_apis.yaml" target="_blank">Download da Especificação (OAS 3.0)</a>

  - name: API - Investimentos - Ações e Fundos de Índices
    description: |
      |Versão|
      |:-----|
      |1.0.0|

      #### Visão Geral

      As instituições financeiras participantes podem consultar a lista de produtos de Renda Variável de outras instituições participantes

      #### Especificação em OAS 3.0

      <a href="swagger/swagger_investments_variable_income_apis.yaml" target="_blank">Download da Especificação (OAS 3.0)</a>

  - name: API - Investimentos - Tesouro
    description: |
      |Versão|
      |:-----|
      |1.0.0|

      #### Visão Geral

      As instituições financeiras participantes podem consultar a lista de Títulos do Tesouro Direto de outras instituições participantes

      #### Especificação em OAS 3.0

      <a href="swagger/swagger_investments_treasure_apis.yaml" target="_blank">Download da Especificação (OAS 3.0)</a>
paths:
  /capitalization-bonds/v1/products:
    get:
      tags:
        - API - Títulos de Capitalização
      summary: Lista de títulos de capitalização
      operationId: capitalizationBondsGetProducts
      description: |
        Método para obter a lista de todos os títulos de Capitalização de uma instituição

        ### Dicionário de dados

        Campos de resposta do endpoint de `/products`

        <a href='dictionary/capitalizationBondsGetProducts_v1.csv' target="_blank">Fazer download do dicionário de dados</a>

        Consulte a seção **Convenções de payload** para obter mais informações sobre [Atributos Obrigatórios / Opcionais](#convencoes-de-propriedade-dos-atributos).

      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseCapitalizationBondsProductsList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /investments/v1/funds:
    get:
      tags:
        - API - Investimentos - Fundos de Investimento
      summary:
      operationId:
      description:
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseCapitalizationBondsProductIdentification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /investments/v1/fixed-income-bank:
    get:
      tags:
        - API - Investimentos - CDB, RDB, LCI e LCA
      summary:
      operationId:
      description:
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseCapitalizationBondsProductIdentification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /investments/v1/fixed-income-credit:
    get:
      tags:
        - API - Investimentos - Debênture, CRI e CRA
      summary:
      operationId:
      description:
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseCapitalizationBondsProductIdentification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /investments/v1/variable-income:
    get:
      tags:
        - API - Investimentos - Ações e Fundos de Índices
      summary:
      operationId:
      description:
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseCapitalizationBondsProductIdentification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /investments/v1/treasure:
    get:
      tags:
        - API - Investimentos - Tesouro Direto
      summary:
      operationId:
      description:
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseCapitalizationBondsProductIdentification'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  schemas:
    ResponseCapitalizationBondsProductsList:
      $ref: ./schemas/capitalization_bonds_apis/ResponseCapitalizationBondsProductsList.yaml
    CapitalizationBondsProduct:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProduct.yaml
    CapitalizationBondsProductEarlyRedemption:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProductEarlyRedemption.yaml
    EnumCapitalizationBondsProductModality:
      $ref: ./schemas/enum/EnumCapitalizationBondsProductModality.yaml
    EnumCapitalizationBondsProductPaymentFrequency:
      $ref: ./schemas/enum/EnumCapitalizationBondsProductPaymentTerm.yaml
    CapitalizationBondsProductIdentificationData:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProductIdentificationData.yaml
    TermsAndConditions:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProductTermsAndConditions.yaml
    CapitalizationBondsProductQuota:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProductQuota.yaml
    CapitalizationPeriod:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProductCapitalizationPeriod.yaml
    LatePayment:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProductLatePayment.yaml
    ContributionPayment:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProductContributionPayment.yaml
    CapitalizationBondsProductPaymentMethod:
      $ref: ./schemas/enum/CapitalizationBondsProductPaymentMethod.yaml
    EnumCapitalizationBondsProductYesOrNoOptions:
      $ref: ./schemas/enum/EnumCapitalizationBondsProductYesOrNoOptions.yaml
    PrizeDraw:
      $ref: ./schemas/capitalization_bonds_apis/CapitalizationBondsProductPrizeDraw.yaml
    EnumCapitalizationBondsFrequency:
      $ref: ./schemas/enum/EnumCapitalizationBondsFrequency.yaml
    EnumTargetAudience:
      $ref: ./schemas/enum/CapitalizationBondsProductEnumTargetAudience.yaml
    Links:
      $ref: ./schemas/Links.yaml
    Meta:
      $ref: ./schemas/Meta.yaml
    ResponseError:
      $ref: ./schemas/ResponseError.yaml
  parameters:
    page:
      $ref: ./parameters/Page.yaml
    pageSize:
      $ref: ./parameters/PageSize.yaml
  responses:
    OKResponseCapitalizationBondsProductsList:
      description: Dados de título(s) de capitalização obtidos com sucesso.
      content:
        application/json:
          schema:
            $ref: ./schemas/capitalization_bonds_apis/ResponseCapitalizationBondsProductsList.yaml
    BadRequest:
      description: 'A requisição foi malformada, omitindo atributos obrigatórios, seja no payload ou através de atributos na URL.'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    InternalServerError:
      description: Ocorreu um erro no gateway da API ou no microsserviço
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    MethodNotAllowed:
      description: O consumidor tentou acessar o recurso com um método não suportado
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    NotFound:
      description: O recurso solicitado não existe ou não foi implementado
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    TooManyRequests:
      description: 'A operação foi recusada, pois muitas solicitações foram feitas dentro de um determinado período ou o limite global de requisições concorrentes foi atingido'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
