openapi: 3.0.0
info:
  title: API Pension - Open Banking Brasil
  description: |
    API de Previdência do Open Banking Brasil – Fase 4.
    API que retorna informações de Previdência.
  version: 1.0.0
  license: 
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
  contact:
    name: Governança do Open Banking Brasil – Especificações
    email: gt-interfaces@openbankingbr.org
    url: 'https://openbanking-brasil.github.io/areadesenvolvedor/'
servers:
  - url: 'https://api.banco.com.br/open-banking/opendata-pension/v1'
    description: Servidor de Produção
  - url: 'https://apih.banco.com.br/open-banking/opendata-pension/v1'
    description: Servidor de Homologação
tags:
  - name: Risk Coverages
    description: Operações relacionadas à Previdência com Coberturas de Risco.
  - name: Survival Coverages
    description: Operações relacionadas à Previdência com Coberturas de Sobrevivência.
paths:
  /risk-coverages:
    get:
      tags:
        - Risk Coverages
      summary: Informações de Previdência com Cobertura de Riscos.
      operationId: getPensionRiskCoverages
      description: Método para obter informações de Previdência de Cobertura de Riscos.
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseRiskCoveragePension'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /survival-coverages:
    get:
      tags:
        - Survival Coverages
      summary: Informações de Previdência com Cobertura de Sobrevivência.
      operationId: getPensionSurvivalCoverages
      description: Método para obter informações de Previdência de Cobertura de Sobrevivência.
      parameters:
        - $ref: '#/components/parameters/page'
        - $ref: '#/components/parameters/pageSize'
      responses:
        '200':
          $ref: '#/components/responses/OKResponseSurvivorCoveragePension'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '405':
          $ref: '#/components/responses/MethodNotAllowed'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  schemas:
    OKResponseRiskCoveragePension:
      $ref: './schemas/pension_apis/risk/OkResponseGetRiskPensionContract.yaml'
    GetRiskPensionContractData:
      $ref: './schemas/pension_apis/risk/GetRiskPensionContractData.yaml'
    OKResponseSurvivalCoveragePension:
      $ref: './schemas/pension_apis/survival/OkResponseGetSurvivalPensionContract.yaml'
    GetSurvivalPensionContractData:
      $ref: './schemas/pension_apis/survival/GetSurvivalPensionContractData.yaml'
    SurvivalPensionInvestimentFund:
      $ref: './schemas/pension_apis/survival/SurvivalPensionInvestimentFund.yaml'
    SurvivalPensionProduct:
      $ref: ./schemas/pension_apis/survival/SurvivalPensionProduct.yaml
    SurvivalPensionMinimumRequirements:
      $ref: ./schemas/pension_apis/survival/SurvivalPensionMinimumRequirements.yaml
    SusepProcessNumber:
      $ref: ./schemas/business_commons/SusepProcessNumber.yaml
    CnpjNumber:
      $ref: ./schemas/business_commons/CnpjNumber.yaml
    SurvivalPensionDefferalPeriod:
      $ref: ./schemas/pension_apis/survival/SurvivalPensionDefferalPeriod.yaml
    SurvivalPensionType:
      $ref: ./schemas/pension_apis/survival/SurvivalPensionType.yaml
    SurvivalPensionGracePeriod:
      $ref: ./schemas/pension_apis/survival/SurvivalGracePeriod.yaml
    SurvivalPensionCosts:
      $ref: ./schemas/pension_apis/survival/SurvivalPensionCosts.yaml
    SurvivalPensionLoadingAntecipated:
      $ref: ./schemas/pension_apis/survival/SurvivalPensionLoadingAntecipated.yaml
    SurvivalPensionLoadingLate:
      $ref: ./schemas/pension_apis/survival/SurvivalPensionLoadingLate.yaml
    SurvivalPensionMinimumPremium:
      $ref: ./schemas/pension_apis/survival/SurvivalPensionMinimumPremium.yaml
    SurvivalPensionGrantPeriodBenefit:
      $ref: ./schemas/pension_apis/survival/SurvivalPensionGrantPeriodBenefit.yaml
    Links:
      $ref: './schemas/Links.yaml'
    Meta:
      $ref: './schemas/Meta.yaml'
    ParticipantIdentification:
      $ref: ./schemas/business_commons/ParticipantIdentification.yaml
    RiskPensionProduct:
      $ref: ./schemas/pension_apis/risk/RiskPensionProduct.yaml
    EnumRiskPensionIndemnifiablePeriod:
      $ref: ./schemas/enum/EnumRiskPensionIndemnifiablePeriod.yaml
    EnumTargetAudience:
      $ref: ./schemas/business_commons/EnumTargetAudience.yaml
    EnumRiskPensionPaymentModality:
      $ref: ./schemas/enum/EnumRiskPensionPaymentModality.yaml
    EnumProductModality:
      $ref: ./schemas/business_commons/EnumProductModality.yaml
    Coverage:
      $ref: ./schemas/pension_apis/risk/RiskPensionCoverage.yaml
    EnumRiskPensionCoverageType:
      $ref: ./schemas/enum/EnumRiskPensionCoverageType.yaml
    CoverageAttributes:
      $ref: ./schemas/pension_apis/risk/RiskPensionCoverageAttributes.yaml
    GracePeriod:
      $ref: ./schemas/pension_apis/risk/RiskPensionGracePeriod.yaml
    ReclaimGracePeriod:
      $ref: ./schemas/pension_apis/risk/RiskPensionReclaimGracePeriod.yaml
    TermsAndConditions:
      $ref: ./schemas/business_commons/TermsAndConditionsItem.yaml
    UpdateIndex:
      $ref: ./schemas/enum/EnumPensionUpdateIndex.yaml
    Reclaim:
      $ref: ./schemas/pension_apis/risk/RiskPensionReclaim.yaml
    ReclaimTable:
      $ref: ./schemas/pension_apis/risk/RiskPensionReclaimTable.yaml
    PmbacRemuneration:
      $ref: ./schemas/pension_apis/risk/RiskPensionPmbacRemuneration.yaml
    BenefitRecalculation:
      $ref: ./schemas/pension_apis/risk/RiskPensionBenefitRecalculation.yaml
    AgeAdjustment:
      $ref: ./schemas/pension_apis/risk/RiskPensionAgeAdjustment.yaml
    CurrencyValue:
      $ref: ./schemas/business_commons/CurrencyValue.yaml
    CurrencyCode:
      $ref: ./schemas/business_commons/CurrencyCode.yaml
    EnumExcludedRisks:
      $ref: ./schemas/business_commons/EnumExcludedRisks.yaml
    EnumAssistanceType:
      $ref: ./schemas/business_commons/EnumAssistanceType.yaml
    EnumAdditional:
      $ref: ./schemas/business_commons/EnumAdditional.yaml
    EnumTerm:
      $ref: ./schemas/business_commons/EnumTerm.yaml
  parameters:
    page:
      $ref: ./parameters/Page.yaml
    pageSize:
      $ref: ./parameters/PageSize.yaml
  responses:
    OKResponseRiskCoveragePension:
      description: 'Dados de previdência de risco obtidos com sucesso da instituição.'
      content:
        application/json:
          schema:
            $ref: './schemas/pension_apis/risk/OkResponseGetRiskPensionContract.yaml'
    OKResponseSurvivorCoveragePension:
      description: 'Dados de previdência de sobrevivência obtidos com sucesso da instituição.'
      content:
        application/json:
          schema:
            $ref: './schemas/pension_apis/survival/OkResponseGetSurvivalPensionContract.yaml'
    BadRequest:
      description: 'A requisição foi malformada, omitindo atributos obrigatórios, seja no payload ou através de atributos na URL.'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    NotFound:
      description: O recurso solicitado não existe ou não foi implementado
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    MethodNotAllowed:
      description: O consumidor tentou acessar o recurso com um método não suportado
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    TooManyRequests:
      description: 'A operação foi recusada, pois muitas solicitações foram feitas dentro de um determinado período ou o limite global de requisições concorrentes foi atingido'
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
    InternalServerError:
      description: Ocorreu um erro no gateway da API ou no microsserviço
      content:
        application/json; charset=utf-8:
          schema:
            $ref: ./schemas/ResponseError.yaml
